Update 24.04 links (#720)
canonical/cn.ubuntu.com pull request #722
Opened 2024-05-24 11:12 UTC by carkod

## Done

[List of work items including drive-bys]

## QA

[List of steps to QA the new features or prove the bug has been resolved]

## Issue / Card

[List of links to Github issues/bugs and cards if needed - e.g. `Fixes #1`]

## Screenshots

[if relevant, include a screenshot]

2024-05-24 11:12 UTC, webteam-app commented
### [<img src='https://assets.ubuntu.com/v1/6baef514-ubuntu-circle-of-friends-large.svg' height=32 width=32> Demo</img>](https://cn-ubuntu-com-722.demos.haus)
### [<img src='https://assets.ubuntu.com/v1/e512b0e2-jenkins.svg' height=32 width=32> Jenkins </img>](https://jenkins.canonical.com/webteam/job/start-demo/13942)
### [<img src='https://assets.ubuntu.com/v1/7144ec6d-logo-jaas-icon.svg' height=32 width=32> demos.haus </img>](https://demos.haus)

2024-05-27 12:55 UTC, akbarkz commented
@carkod you branch seems to be outdated from the base branch, can you rebase please?

2024-05-28 10:29 UTC, carkod commented
@britneywwc can you review/proofread? Thanks

2024-05-29 08:10 UTC, britneywwc requested changes

2024-05-29 08:10 UTC, britneywwc commented on templates/download/desktop.html
> +        <p><small>如需其他版本的Ubuntu桌面，请参考Ubuntu桌面的<a href="https://ubuntu.com/desktop">更多信</a></small></p>
```suggestion
        <p><small>如需其他版本的Ubuntu，请参考Ubuntu桌面的<a href="https://ubuntu.com/desktop">更多信息</a></small></p>
```

2024-05-29 12:15 UTC, britneywwc approved these changes
LGTM 谢谢!

2024-05-29 17:07 UTC, carkod commented
> LGTM 谢谢!

谢谢你

2024-05-29 17:07 UTC, merged